### ISSUE TITLE
Room corners detection 

### ISSUE THREAD

**Issue by ebrahimkhalilabbasi** [bjekic/WallSegmentation#11]
Hello, 

Is it possible to use the result of this work to detect the corners of the room?

**Comment by bjekic** [comment]
Hi @ebrahimkhalilabbasi,

The task of detecting corners is not part of the task solved in this repository. But you can further use the output of this network in any way you want.

**Comment by ebrahimkhalilabbasi** [comment]
@bjekic thanks for your quick answer. Is it possible, for example, to get the length and width of the walls?

**Comment by bjekic** [comment]
Hi @ebrahimkhalilabbasi,

Your tasks seem to be outside of the scope of this repository. I'm sorry but I cannot be of more help.
